using ExampleApp.IntegrationTests.Environment;

namespace ExampleApp.IntegrationTests;

public class DuplicatePermissionValidationTestsImpl(IServiceProvider rootServiceProvider) : DuplicatePermissionValidationTests(rootServiceProvider);