using ExampleApp.IntegrationTests.Environment;

namespace ExampleApp.IntegrationTests;

public class PermissionExtendedDataTestsImpl(IServiceProvider rootServiceProvider) : PermissionExtendedDataTests(rootServiceProvider);