using ExampleApp.IntegrationTests.Environment;

namespace ExampleApp.IntegrationTests;

public class PermissionDelegationFromTestsImpl(IServiceProvider rootServiceProvider) : PermissionDelegationFromTests(rootServiceProvider);